# Generated by Django 4.2.6 on 2023-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец обеда')),
            ],
            options={
                'verbose_name': 'Обеденный перерыв',
                'verbose_name_plural': 'Обеденный перерывы',
                'ordering': ('-replacement__date', 'break_start'),
            },
        ),
        migrations.CreateModel(
            name='BreakStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус обеда',
                'verbose_name_plural': 'Статусы обеда',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('min_active', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Минимальное количество активных сотрудников')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец обеда')),
                ('break_max_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальная длительность обеда')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Гоуппы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организация',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('break_start', models.TimeField(verbose_name='Начало обеда')),
                ('break_end', models.TimeField(verbose_name='Конец обеда')),
                ('break_max_duration', models.PositiveSmallIntegerField(verbose_name='Макс. продолжительность обеда')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ReplacementEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Смена - Работник',
                'verbose_name_plural': 'Смены - Работники',
            },
        ),
        migrations.CreateModel(
            name='ReplacementStatus',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='Код')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('sort', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Статус смены',
                'verbose_name_plural': 'Статусы смены',
            },
        ),
    ]
