# Generated by Django 4.2.6 on 2023-11-09 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacementemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='replacementemployee',
            name='replacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='breaks.replacement', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='replacementemployee',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='replacement_employees', to='breaks.replacementstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='replacement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='breaks.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organisation_directors', to=settings.AUTH_USER_MODEL, verbose_name='Директор'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='organisations_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='group',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='group_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='group_managers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='group',
            name='organisations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='breaks.organisation', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='break',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='break',
            name='replacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='breaks.replacement', verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='break',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='breaks', to='breaks.breakstatus', verbose_name='Статус'),
        ),
    ]
