# Generated by Django 4.2.6 on 2023-10-25 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='organisations_employees', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
