# Generated by Django 4.2.6 on 2023-10-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='organisations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='groups', to='breaks.organisation', verbose_name='Организация'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
