# Generated by Django 4.2.6 on 2023-10-25 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaks', '0005_alter_group_organisations_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organisation_directors', to=settings.AUTH_USER_MODEL, verbose_name='Директор'),
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('break_start', models.TimeField(verbose_name='Начало обеда')),
                ('break_end', models.TimeField(verbose_name='Конец обеда')),
                ('break_max_duration', models.PositiveSmallIntegerField(verbose_name='Макс. продолжительность обеда')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='breaks.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-date',),
            },
        ),
    ]
