# Generated by Django 4.2.6 on 2023-10-28 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaks', '0007_replacementstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='breaks.replacement', verbose_name='Смена')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='replacement_employees', to='breaks.replacementstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Смена - Работник',
                'verbose_name_plural': 'Смены - Работники',
            },
        ),
    ]
