# Generated by Django 4.2.6 on 2023-10-28 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('breaks', '0009_breakstatus_alter_replacementstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakstatus',
            options={'verbose_name': 'Статус обеда', 'verbose_name_plural': 'Статусы обеда'},
        ),
        migrations.AlterModelOptions(
            name='replacementstatus',
            options={'verbose_name': 'Статус смены', 'verbose_name_plural': 'Статусы смены'},
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Начало обеда')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Конец обеда')),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Продолжитнльность обеда')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='breaks.replacement', verbose_name='Смена')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='breaks', to='breaks.breakstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Обед',
                'verbose_name_plural': 'Обеды',
                'ordering': ('-replacement__date', 'break_start'),
            },
        ),
    ]
