# Generated by Django 4.2.6 on 2023-10-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0010_alter_breakstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='break',
            options={'ordering': ('-replacement__date', 'break_start'), 'verbose_name': 'Обеденный перерыв', 'verbose_name_plural': 'Обеденный перерывы'},
        ),
    ]
