# Generated by Django 4.2.6 on 2023-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0011_alter_break_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakstatus',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='replacementstatus',
            name='sort',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
    ]
