# Generated by Django 4.2.6 on 2023-10-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0012_alter_breakstatus_sort_alter_replacementstatus_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='duration',
        ),
    ]
